-- Migration 0006: Meals, grocery carts, weekly reports
-- Rollback: supabase/migrations/rollback/0006_rollback.sql
-- Validate: supabase/migrations/validate/0006_validate.sql
--
-- Design notes:
--   meal_logs: nutrition at serving is computed by the engine from product_nutrition,
--     never set by LLM. is_estimated = true when portion is AI-estimated (D4 honesty).
--   weekly_reports: narrative is LLM-generated but policy-checked before write;
--     all aggregate numbers are computed, not LLM-generated.

-- ---------------------------------------------------------------------------
-- meal_logs
-- ---------------------------------------------------------------------------
CREATE TABLE public.meal_logs (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- member_id NULL = log for the head user themselves
  member_id            UUID         REFERENCES public.household_members(id) ON DELETE SET NULL,
  meal_type            TEXT         NOT NULL CHECK (meal_type IN ('breakfast','lunch','dinner','snack','other')),
  logged_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  -- Food reference: product-linked or free-text entry
  product_id           UUID         REFERENCES public.products(id) ON DELETE SET NULL,
  food_name            TEXT         NOT NULL,
  quantity_g           NUMERIC(8,2) CHECK (quantity_g > 0),
  portion_description  TEXT,
  -- Serving nutrition (computed by engine; not set by LLM)
  energy_kcal          NUMERIC(8,2),
  protein_g            NUMERIC(8,3),
  fat_total_g          NUMERIC(8,3),
  carbohydrates_g      NUMERIC(8,3),
  sugars_g             NUMERIC(8,3),
  dietary_fiber_g      NUMERIC(8,3),
  sodium_mg            NUMERIC(8,2),
  -- Confidence: 0–1; shown in UI when is_estimated = true (D4)
  portion_confidence   NUMERIC(4,3) CHECK (portion_confidence BETWEEN 0 AND 1),
  nutrition_source     TEXT         REFERENCES public.data_sources(id),
  is_estimated         BOOLEAN      NOT NULL DEFAULT false,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX meal_logs_user_date_idx  ON public.meal_logs(user_id, logged_at DESC);
CREATE INDEX meal_logs_member_idx     ON public.meal_logs(member_id) WHERE member_id IS NOT NULL;
CREATE INDEX meal_logs_product_idx    ON public.meal_logs(product_id) WHERE product_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- grocery_cart_sessions
-- ---------------------------------------------------------------------------
CREATE TABLE public.grocery_cart_sessions (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name         TEXT,
  status       TEXT        NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','abandoned')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX grocery_cart_sessions_user_idx    ON public.grocery_cart_sessions(user_id, created_at DESC);
CREATE INDEX grocery_cart_sessions_status_idx  ON public.grocery_cart_sessions(user_id, status) WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- grocery_cart_items
-- ---------------------------------------------------------------------------
CREATE TABLE public.grocery_cart_items (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  cart_session_id  UUID        NOT NULL REFERENCES public.grocery_cart_sessions(id) ON DELETE CASCADE,
  product_id       UUID        NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity         SMALLINT    NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX grocery_cart_items_session_idx ON public.grocery_cart_items(cart_session_id);
CREATE UNIQUE INDEX grocery_cart_items_unique_product
  ON public.grocery_cart_items(cart_session_id, product_id);

-- ---------------------------------------------------------------------------
-- weekly_reports  (generated by pg-boss worker job)
-- ---------------------------------------------------------------------------
CREATE TABLE public.weekly_reports (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start       DATE         NOT NULL,
  week_end         DATE         NOT NULL,
  generated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  -- Aggregate nutrition stats (computed, not LLM-generated)
  avg_daily_kcal   NUMERIC(8,2),
  avg_protein_g    NUMERIC(8,3),
  avg_fat_g        NUMERIC(8,3),
  avg_carbs_g      NUMERIC(8,3),
  avg_sodium_mg    NUMERIC(8,2),
  scan_count       INTEGER      NOT NULL DEFAULT 0,
  -- LLM-generated narrative (policy-checked; disclaimer always present)
  narrative        TEXT,
  narrative_disclaimer TEXT,
  -- Full weekly breakdown for UI rendering
  report_data      JSONB,
  -- pg-boss job traceability
  job_id           TEXT,
  UNIQUE (user_id, week_start)
);

CREATE INDEX weekly_reports_user_idx ON public.weekly_reports(user_id, week_start DESC);
