-- Migration: 0024_seasonal_produce_seed
-- Purpose: Seed seasonal_produce (added in 0023) with real, cited monthly calendars for the 8
-- Tier-1 countries. Generated from apps/api/src/memory/seasonal-produce-data.ts (the canonical
-- TS source — keep both in sync if either changes; see that file's header comment).
-- Singapore (SG) is intentionally absent: >90% of its food is imported (Singapore Food Agency)
-- and there is no meaningful domestic seasonal calendar to cite — an empty result for SG is the
-- honest answer, not a gap to fill with invented data.
-- Rollback: see 0024_seasonal_produce_seed_rollback.sql

BEGIN;

INSERT INTO public.seasonal_produce (country_code, region, month, items, source) VALUES
('IN', NULL, 1, ARRAY['spinach','carrot','cauliflower','peas','fenugreek','orange'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 2, ARRAY['spinach','carrot','cauliflower','peas','strawberry'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 3, ARRAY['mango','watermelon','cucumber','bottle gourd'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 4, ARRAY['mango','watermelon','muskmelon','jackfruit'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 5, ARRAY['mango','litchi','watermelon','jackfruit'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 6, ARRAY['mango','litchi','jamun','cucumber'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 7, ARRAY['jamun','okra','bitter gourd','ridge gourd'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 8, ARRAY['okra','bitter gourd','apple','pear'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 9, ARRAY['pomegranate','guava','okra'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 10, ARRAY['pomegranate','guava','sweet potato','carrot'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 11, ARRAY['carrot','cauliflower','peas','radish','orange'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('IN', NULL, 12, ARRAY['carrot','cauliflower','peas','radish','orange','strawberry'], 'ICAR crop calendar / National Horticulture Board seasonal availability charts'),
('US', NULL, 1, ARRAY['kale','sweet potato','grapefruit','cabbage'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 2, ARRAY['kale','sweet potato','orange','cabbage'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 3, ARRAY['artichoke','asparagus','spinach'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 4, ARRAY['asparagus','spinach','strawberry'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 5, ARRAY['strawberry','asparagus','peas'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 6, ARRAY['strawberry','blueberry','zucchini','corn'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 7, ARRAY['corn','tomato','peach','watermelon'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 8, ARRAY['corn','tomato','peach','watermelon'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 9, ARRAY['apple','pumpkin','grape','pear'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 10, ARRAY['apple','pumpkin','squash','pear'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 11, ARRAY['squash','cranberry','sweet potato','brussels sprout'], 'USDA seasonal produce guide (nationwide average)'),
('US', NULL, 12, ARRAY['cranberry','sweet potato','brussels sprout','citrus'], 'USDA seasonal produce guide (nationwide average)'),
('GB', NULL, 1, ARRAY['leek','parsnip','swede','brussels sprout'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 2, ARRAY['leek','parsnip','purple sprouting broccoli'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 3, ARRAY['purple sprouting broccoli','spring onion','rhubarb'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 4, ARRAY['rhubarb','asparagus','spinach'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 5, ARRAY['asparagus','new potato','strawberry'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 6, ARRAY['strawberry','broad bean','pea','cherry'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 7, ARRAY['broad bean','courgette','raspberry','cherry'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 8, ARRAY['tomato','sweetcorn','plum','blackberry'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 9, ARRAY['apple','pear','plum','pumpkin'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 10, ARRAY['apple','pumpkin','squash','parsnip'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 11, ARRAY['parsnip','swede','brussels sprout','leek'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('GB', NULL, 12, ARRAY['brussels sprout','parsnip','swede','leek'], 'Eat Seasonably (UK Food & Drink Federation) seasonal calendar'),
('AE', NULL, 1, ARRAY['tomato','cucumber','eggplant','date'], 'UAE Ministry of Climate Change & Environment — winter desert-farming produce (Nov-Mar); no meaningful summer domestic season'),
('AE', NULL, 2, ARRAY['tomato','cucumber','eggplant'], 'UAE Ministry of Climate Change & Environment — winter desert-farming produce (Nov-Mar); no meaningful summer domestic season'),
('AE', NULL, 3, ARRAY['tomato','cucumber','eggplant'], 'UAE Ministry of Climate Change & Environment — winter desert-farming produce (Nov-Mar); no meaningful summer domestic season'),
('AE', NULL, 11, ARRAY['tomato','cucumber','eggplant','date'], 'UAE Ministry of Climate Change & Environment — winter desert-farming produce (Nov-Mar); no meaningful summer domestic season'),
('AE', NULL, 12, ARRAY['tomato','cucumber','eggplant','date'], 'UAE Ministry of Climate Change & Environment — winter desert-farming produce (Nov-Mar); no meaningful summer domestic season'),
('AU', NULL, 1, ARRAY['mango','stone fruit','zucchini','corn'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 2, ARRAY['stone fruit','tomato','corn'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 3, ARRAY['fig','grape','pear'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 4, ARRAY['apple','pear','pumpkin'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 5, ARRAY['pumpkin','sweet potato','orange'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 6, ARRAY['orange','broccoli','cauliflower'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 7, ARRAY['broccoli','cauliflower','leek'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 8, ARRAY['leek','silverbeet','kiwifruit'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 9, ARRAY['asparagus','strawberry','spinach'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 10, ARRAY['asparagus','strawberry','pea'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 11, ARRAY['cherry','mango','pea'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('AU', NULL, 12, ARRAY['cherry','mango','stone fruit'], 'Hort Innovation Australia seasonal produce guide (Southern Hemisphere)'),
('CA', NULL, 1, ARRAY['squash','cabbage','potato','carrot'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 2, ARRAY['squash','cabbage','potato'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 3, ARRAY['maple syrup','potato','cabbage'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 4, ARRAY['asparagus','rhubarb'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 5, ARRAY['asparagus','rhubarb','radish'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 6, ARRAY['strawberry','pea','lettuce'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 7, ARRAY['strawberry','blueberry','corn','zucchini'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 8, ARRAY['corn','tomato','peach','blueberry'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 9, ARRAY['apple','pumpkin','grape'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 10, ARRAY['apple','pumpkin','squash'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 11, ARRAY['squash','cabbage','carrot'], 'Foodland Ontario seasonal availability guide'),
('CA', NULL, 12, ARRAY['squash','cabbage','carrot','potato'], 'Foodland Ontario seasonal availability guide'),
('DE', NULL, 1, ARRAY['kale','leek','cabbage','parsnip'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 2, ARRAY['kale','leek','cabbage'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 3, ARRAY['spinach','radish','rhubarb'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 4, ARRAY['asparagus','spinach','radish'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 5, ARRAY['asparagus','strawberry','radish'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 6, ARRAY['strawberry','cherry','pea'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 7, ARRAY['cherry','blueberry','cucumber','tomato'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 8, ARRAY['plum','tomato','zucchini'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 9, ARRAY['apple','pear','pumpkin','plum'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 10, ARRAY['apple','pumpkin','squash'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 11, ARRAY['kale','cabbage','leek'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender'),
('DE', NULL, 12, ARRAY['kale','cabbage','leek','parsnip'], 'Bundeszentrum für Ernährung (BZfE) Saisonkalender')
ON CONFLICT (country_code, COALESCE(region, ''), month) DO UPDATE SET items = EXCLUDED.items, source = EXCLUDED.source;

COMMIT;
